# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.events import Event

if TYPE_CHECKING:
    from java import JavaObject

_PluginEvent = _java.type("com.hypixel.hytale.server.core.plugin.event.PluginEvent")

_PluginSetupEvent = _java.type(
    "com.hypixel.hytale.server.core.plugin.event.PluginSetupEvent"
)


class PluginEvent(Event):
    _java_class = _PluginEvent

    @property
    def plugin(self) -> "JavaObject":
        return self._java.getPlugin()


class PluginSetupEvent(PluginEvent):
    _java_class = _PluginSetupEvent
