# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit

from uuid import UUID

import java as _java
from pytale._uuid import java_uuid_to_python, python_uuid_to_java
from pytale.components import Component

_CreativeHubEntityConfig = _java.type(
    "com.hypixel.hytale.builtin.creativehub.config.CreativeHubEntityConfig"
)


class CreativeHubEntityConfig(Component):
    _java_class = _CreativeHubEntityConfig

    @property
    def parent_hub_world_uuid(self) -> UUID | None:
        _value = self._java.getParentHubWorldUuid()
        return java_uuid_to_python(_value) if _value is not None else None

    @parent_hub_world_uuid.setter
    def parent_hub_world_uuid(self, value: UUID) -> None:
        self._java.setParentHubWorldUuid(python_uuid_to_java(value))
