# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING
from uuid import UUID

import java as _java
from pytale._uuid import java_uuid_to_python, python_uuid_to_java
from pytale.components import Component
from pytale.math import Rotation3, Vector3

if TYPE_CHECKING:
    from java import JavaObject

_ConfigurableInstanceBlock = _java.type(
    "com.hypixel.hytale.builtin.instances.blocks.ConfigurableInstanceBlock"
)

_InstanceBlock = _java.type("com.hypixel.hytale.builtin.instances.blocks.InstanceBlock")


class ConfigurableInstanceBlock(Component):
    _java_class = _ConfigurableInstanceBlock

    @property
    def instance_key(self) -> str:
        return self._java.getInstanceKey()

    @instance_key.setter
    def instance_key(self, value: str) -> None:
        self._java.setInstanceKey(value)

    @property
    def instance_name(self) -> str:
        return self._java.getInstanceName()

    @instance_name.setter
    def instance_name(self, value: str) -> None:
        self._java.setInstanceName(value)

    @property
    def is_close_on_remove(self) -> bool:
        return self._java.isCloseOnRemove()

    @is_close_on_remove.setter
    def is_close_on_remove(self, value: bool) -> None:
        self._java.setCloseOnRemove(value)

    @property
    def is_personal_return_point(self) -> bool:
        return self._java.isPersonalReturnPoint()

    @is_personal_return_point.setter
    def is_personal_return_point(self, value: bool) -> None:
        self._java.setPersonalReturnPoint(value)

    @property
    def position_offset(self) -> Vector3 | None:
        _value = self._java.getPositionOffset()
        return Vector3(_value) if _value is not None else None

    @position_offset.setter
    def position_offset(self, value: Vector3) -> None:
        self._java.setPositionOffset(value._java)

    @property
    def remove_block_after(self) -> float:
        return self._java.getRemoveBlockAfter()

    @remove_block_after.setter
    def remove_block_after(self, value: float) -> None:
        self._java.setRemoveBlockAfter(value)

    @property
    def rotation(self) -> Rotation3 | None:
        _value = self._java.getRotation()
        return Rotation3(_value) if _value is not None else None

    @rotation.setter
    def rotation(self, value: Rotation3) -> None:
        self._java.setRotation(value._java)

    @property
    def world_future(self) -> "JavaObject":
        return self._java.getWorldFuture()

    @world_future.setter
    def world_future(self, value: "JavaObject") -> None:
        self._java.setWorldFuture(value)

    @property
    def world_uuid(self) -> UUID:
        return java_uuid_to_python(self._java.getWorldUUID())

    @world_uuid.setter
    def world_uuid(self, value: UUID) -> None:
        self._java.setWorldUUID(python_uuid_to_java(value))


class InstanceBlock(Component):
    _java_class = _InstanceBlock

    @property
    def is_close_on_remove(self) -> bool:
        return self._java.isCloseOnRemove()

    @is_close_on_remove.setter
    def is_close_on_remove(self, value: bool) -> None:
        self._java.setCloseOnRemove(value)

    @property
    def world_future(self) -> "JavaObject":
        return self._java.getWorldFuture()

    @world_future.setter
    def world_future(self, value: "JavaObject") -> None:
        self._java.setWorldFuture(value)

    @property
    def world_uuid(self) -> UUID:
        return java_uuid_to_python(self._java.getWorldUUID())

    @world_uuid.setter
    def world_uuid(self, value: UUID) -> None:
        self._java.setWorldUUID(python_uuid_to_java(value))
