# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING
from uuid import UUID

import java as _java
from pytale._uuid import java_uuid_to_python
from pytale.components import Component
from pytale.players import PlayerRef

if TYPE_CHECKING:
    from java import JavaObject

_BlockEntity = _java.type("com.hypixel.hytale.server.core.entity.entities.BlockEntity")

_Player = _java.type("com.hypixel.hytale.server.core.entity.entities.Player")

_ProjectileComponent = _java.type(
    "com.hypixel.hytale.server.core.entity.entities.ProjectileComponent"
)


class BlockEntity(Component):
    _java_class = _BlockEntity

    @property
    def block_type_key(self) -> str:
        return self._java.getBlockTypeKey()

    @property
    def simple_physics_provider(self) -> "JavaObject":
        return self._java.getSimplePhysicsProvider()


class Player(Component):
    _java_class = _Player

    @property
    def client_view_radius(self) -> int:
        return self._java.getClientViewRadius()

    @client_view_radius.setter
    def client_view_radius(self, value: int) -> None:
        self._java.setClientViewRadius(value)

    @property
    def game_mode(self) -> "JavaObject":
        return self._java.getGameMode()

    @property
    def hotbar_manager(self) -> "JavaObject":
        return self._java.getHotbarManager()

    @property
    def hud_manager(self) -> "JavaObject":
        return self._java.getHudManager()

    @property
    def is_first_spawn(self) -> bool:
        return self._java.isFirstSpawn()

    @is_first_spawn.setter
    def is_first_spawn(self, value: bool) -> None:
        self._java.setFirstSpawn(value)

    @property
    def is_override_block_placement_restrictions(self) -> bool:
        return self._java.isOverrideBlockPlacementRestrictions()

    @property
    def is_waiting_for_client_ready(self) -> bool:
        return self._java.isWaitingForClientReady()

    @property
    def mount_entity_id(self) -> int:
        return self._java.getMountEntityId()

    @mount_entity_id.setter
    def mount_entity_id(self, value: int) -> None:
        self._java.setMountEntityId(value)

    @property
    def page_manager(self) -> "JavaObject":
        return self._java.getPageManager()

    @property
    def player_config_data(self) -> "JavaObject":
        return self._java.getPlayerConfigData()

    @property
    def player_connection(self) -> "JavaObject":
        return self._java.getPlayerConnection()

    @property
    def player_ref(self) -> PlayerRef:
        return PlayerRef(self._java.getPlayerRef())

    @property
    def since_last_spawn_nanos(self) -> int:
        return self._java.getSinceLastSpawnNanos()

    @property
    def view_radius(self) -> int:
        return self._java.getViewRadius()

    @property
    def window_manager(self) -> "JavaObject":
        return self._java.getWindowManager()

    @property
    def world_map_tracker(self) -> "JavaObject":
        return self._java.getWorldMapTracker()


class ProjectileComponent(Component):
    _java_class = _ProjectileComponent

    @property
    def appearance(self) -> str:
        return self._java.getAppearance()

    @property
    def creator_uuid(self) -> UUID:
        return java_uuid_to_python(self._java.getCreatorUuid())

    @property
    def is_on_ground(self) -> bool:
        return self._java.isOnGround()

    @property
    def projectile(self) -> "JavaObject | None":
        return self._java.getProjectile()

    @property
    def projectile_asset_name(self) -> str:
        return self._java.getProjectileAssetName()

    @property
    def simple_physics_provider(self) -> "JavaObject":
        return self._java.getSimplePhysicsProvider()
