# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.events import Event

if TYPE_CHECKING:
    from java import JavaObject

_SingleplayerRequestAccessEvent = _java.type(
    "com.hypixel.hytale.server.core.modules.singleplayer.SingleplayerRequestAccessEvent"
)


class SingleplayerRequestAccessEvent(Event):
    _java_class = _SingleplayerRequestAccessEvent

    @property
    def access(self) -> "JavaObject":
        return self._java.getAccess()
