# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING
from uuid import UUID

import java as _java
from pytale._uuid import java_uuid_to_python, python_uuid_to_java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_Flock = _java.type("com.hypixel.hytale.server.flock.Flock")

_FlockMembership = _java.type("com.hypixel.hytale.server.flock.FlockMembership")

_PersistentFlockData = _java.type("com.hypixel.hytale.server.flock.PersistentFlockData")


class Flock(Component):
    _java_class = _Flock

    @property
    def damage_data(self) -> "JavaObject":
        return self._java.getDamageData()

    @property
    def flock_data(self) -> "JavaObject":
        return self._java.getFlockData()

    @flock_data.setter
    def flock_data(self, value: "JavaObject") -> None:
        self._java.setFlockData(value)

    @property
    def is_trace(self) -> bool:
        return self._java.isTrace()

    @is_trace.setter
    def is_trace(self, value: bool) -> None:
        self._java.setTrace(value)

    @property
    def leader_damage_data(self) -> "JavaObject":
        return self._java.getLeaderDamageData()

    @property
    def next_damage_data(self) -> "JavaObject":
        return self._java.getNextDamageData()

    @property
    def next_leader_damage_data(self) -> "JavaObject":
        return self._java.getNextLeaderDamageData()

    @property
    def removed_status(self) -> "JavaObject":
        return self._java.getRemovedStatus()

    @removed_status.setter
    def removed_status(self, value: "JavaObject") -> None:
        self._java.setRemovedStatus(value)


class FlockMembership(Component):
    _java_class = _FlockMembership

    @property
    def flock_id(self) -> UUID:
        return java_uuid_to_python(self._java.getFlockId())

    @flock_id.setter
    def flock_id(self, value: UUID) -> None:
        self._java.setFlockId(python_uuid_to_java(value))

    @property
    def flock_ref(self) -> "JavaObject | None":
        return self._java.getFlockRef()

    @flock_ref.setter
    def flock_ref(self, value: "JavaObject") -> None:
        self._java.setFlockRef(value)

    @property
    def membership_type(self) -> "JavaObject":
        return self._java.getMembershipType()

    @membership_type.setter
    def membership_type(self, value: "JavaObject") -> None:
        self._java.setMembershipType(value)


class PersistentFlockData(Component):
    _java_class = _PersistentFlockData

    @property
    def max_grow_size(self) -> int:
        return self._java.getMaxGrowSize()
