# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING
from uuid import UUID

import java as _java
from pytale._uuid import java_uuid_to_python
from pytale.components import Component
from pytale.world import World

if TYPE_CHECKING:
    from java import JavaObject

_Entity = _java.type("com.hypixel.hytale.server.core.entity.Entity")

_Frozen = _java.type("com.hypixel.hytale.server.core.entity.Frozen")

_InteractionManager = _java.type(
    "com.hypixel.hytale.server.core.entity.InteractionManager"
)

_LivingEntity = _java.type("com.hypixel.hytale.server.core.entity.LivingEntity")

_UUIDComponent = _java.type("com.hypixel.hytale.server.core.entity.UUIDComponent")


class Entity(Component):
    _java_class = _Entity

    @property
    def is_collidable(self) -> bool:
        return self._java.isCollidable()

    @property
    def legacy_display_name(self) -> str:
        return self._java.getLegacyDisplayName()

    @property
    def network_id(self) -> int:
        return self._java.getNetworkId()

    @property
    def reference(self) -> "JavaObject | None":
        return self._java.getReference()

    @reference.setter
    def reference(self, value: "JavaObject") -> None:
        self._java.setReference(value)

    @property
    def uuid(self) -> UUID | None:
        _value = self._java.getUuid()
        return java_uuid_to_python(_value) if _value is not None else None

    @property
    def world(self) -> World | None:
        _value = self._java.getWorld()
        return World(_value) if _value is not None else None


class LivingEntity(Entity):
    _java_class = _LivingEntity

    @property
    def current_fall_distance(self) -> float:
        return self._java.getCurrentFallDistance()

    @current_fall_distance.setter
    def current_fall_distance(self, value: float) -> None:
        self._java.setCurrentFallDistance(value)

    @property
    def inventory(self) -> "JavaObject":
        return self._java.getInventory()


class Frozen(Component):
    _java_class = _Frozen


class InteractionManager(Component):
    _java_class = _InteractionManager

    @property
    def chains(self) -> "JavaObject":
        return self._java.getChains()

    @property
    def interaction_simulation_handler(self) -> "JavaObject":
        return self._java.getInteractionSimulationHandler()

    @property
    def sync_packets(self) -> "JavaObject":
        return self._java.getSyncPackets()


class UUIDComponent(Component):
    _java_class = _UUIDComponent

    @property
    def uuid(self) -> UUID:
        return java_uuid_to_python(self._java.getUuid())
