# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.events import Cancellable, Event

if TYPE_CHECKING:
    from java import JavaObject

_ModifyWarpEvent = _java.type(
    "com.hypixel.hytale.builtin.teleport.commands.event.ModifyWarpEvent"
)

_RemoveWarpEvent = _java.type(
    "com.hypixel.hytale.builtin.teleport.commands.event.RemoveWarpEvent"
)

_ReplaceWarpEvent = _java.type(
    "com.hypixel.hytale.builtin.teleport.commands.event.ReplaceWarpEvent"
)


class ModifyWarpEvent(Event, Cancellable):
    _java_class = _ModifyWarpEvent

    @property
    def cancel_reason(self) -> "JavaObject | None":
        return self._java.getCancelReason()

    @property
    def warp(self) -> "JavaObject":
        return self._java.getWarp()


class RemoveWarpEvent(ModifyWarpEvent, Cancellable):
    _java_class = _RemoveWarpEvent


class ReplaceWarpEvent(ModifyWarpEvent, Cancellable):
    _java_class = _ReplaceWarpEvent
