# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit

from uuid import UUID

import java as _java
from pytale._uuid import java_uuid_to_python
from pytale.components import Component

_PredictedProjectile = _java.type(
    "com.hypixel.hytale.server.core.modules.projectile.component.PredictedProjectile"
)

_Projectile = _java.type(
    "com.hypixel.hytale.server.core.modules.projectile.component.Projectile"
)


class PredictedProjectile(Component):
    _java_class = _PredictedProjectile

    @property
    def uuid(self) -> UUID:
        return java_uuid_to_python(self._java.getUuid())


class Projectile(Component):
    _java_class = _Projectile
