# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING
from uuid import UUID

import java as _java
from pytale._uuid import java_uuid_to_python
from pytale.components import Component
from pytale.math import Vector3

if TYPE_CHECKING:
    from java import JavaObject

_StandardPhysicsProvider = _java.type(
    "com.hypixel.hytale.server.core.modules.projectile.config.StandardPhysicsProvider"
)


class StandardPhysicsProvider(Component):
    _java_class = _StandardPhysicsProvider

    @property
    def block_collision_provider(self) -> "JavaObject":
        return self._java.getBlockCollisionProvider()

    @property
    def bounce_consumer(self) -> "JavaObject | None":
        return self._java.getBounceConsumer()

    @bounce_consumer.setter
    def bounce_consumer(self, value: "JavaObject") -> None:
        self._java.setBounceConsumer(value)

    @property
    def bounces(self) -> int:
        return self._java.getBounces()

    @property
    def collision_start(self) -> float:
        return self._java.getCollisionStart()

    @collision_start.setter
    def collision_start(self, value: float) -> None:
        self._java.setCollisionStart(value)

    @property
    def contact_normal(self) -> Vector3:
        return Vector3(self._java.getContactNormal())

    @property
    def contact_position(self) -> Vector3:
        return Vector3(self._java.getContactPosition())

    @property
    def creator_uuid(self) -> UUID | None:
        _value = self._java.getCreatorUuid()
        return java_uuid_to_python(_value) if _value is not None else None

    @property
    def displaced_mass(self) -> float:
        return self._java.getDisplacedMass()

    @displaced_mass.setter
    def displaced_mass(self, value: float) -> None:
        self._java.setDisplacedMass(value)

    @property
    def enter_fluid(self) -> float:
        return self._java.getEnterFluid()

    @enter_fluid.setter
    def enter_fluid(self, value: float) -> None:
        self._java.setEnterFluid(value)

    @property
    def entity_collision_provider(self) -> "JavaObject":
        return self._java.getEntityCollisionProvider()

    @property
    def fluid_tracker(self) -> "JavaObject":
        return self._java.getFluidTracker()

    @property
    def force_provider_entity(self) -> "JavaObject":
        return self._java.getForceProviderEntity()

    @property
    def force_provider_standard_state(self) -> "JavaObject":
        return self._java.getForceProviderStandardState()

    @property
    def force_providers(self) -> "JavaObject":
        return self._java.getForceProviders()

    @property
    def impact_consumer(self) -> "JavaObject | None":
        return self._java.getImpactConsumer()

    @impact_consumer.setter
    def impact_consumer(self, value: "JavaObject") -> None:
        self._java.setImpactConsumer(value)

    @property
    def is_bounced(self) -> bool:
        return self._java.isBounced()

    @is_bounced.setter
    def is_bounced(self, value: bool) -> None:
        self._java.setBounced(value)

    @property
    def is_in_fluid(self) -> bool:
        return self._java.isInFluid()

    @is_in_fluid.setter
    def is_in_fluid(self, value: bool) -> None:
        self._java.setInFluid(value)

    @property
    def is_moved_inside_solid(self) -> bool:
        return self._java.isMovedInsideSolid()

    @is_moved_inside_solid.setter
    def is_moved_inside_solid(self, value: bool) -> None:
        self._java.setMovedInsideSolid(value)

    @property
    def is_on_ground(self) -> bool:
        return self._java.isOnGround()

    @is_on_ground.setter
    def is_on_ground(self, value: bool) -> None:
        self._java.setOnGround(value)

    @property
    def is_provides_character_collisions(self) -> bool:
        return self._java.isProvidesCharacterCollisions()

    @property
    def is_sliding(self) -> bool:
        return self._java.isSliding()

    @is_sliding.setter
    def is_sliding(self, value: bool) -> None:
        self._java.setSliding(value)

    @property
    def is_swimming(self) -> bool:
        return self._java.isSwimming()

    @property
    def leave_fluid(self) -> float:
        return self._java.getLeaveFluid()

    @leave_fluid.setter
    def leave_fluid(self, value: float) -> None:
        self._java.setLeaveFluid(value)

    @property
    def move_out_of_solid_velocity(self) -> Vector3:
        return Vector3(self._java.getMoveOutOfSolidVelocity())

    @property
    def movement(self) -> Vector3:
        return Vector3(self._java.getMovement())

    @property
    def next_movement(self) -> Vector3:
        return Vector3(self._java.getNextMovement())

    @property
    def physics_config(self) -> "JavaObject":
        return self._java.getPhysicsConfig()

    @property
    def position(self) -> Vector3:
        return Vector3(self._java.getPosition())

    @property
    def resting_support(self) -> "JavaObject":
        return self._java.getRestingSupport()

    @property
    def state(self) -> "JavaObject":
        return self._java.getState()

    @state.setter
    def state(self, value: "JavaObject") -> None:
        self._java.setState(value)

    @property
    def state_after(self) -> "JavaObject":
        return self._java.getStateAfter()

    @property
    def state_before(self) -> "JavaObject":
        return self._java.getStateBefore()

    @property
    def state_updater(self) -> "JavaObject":
        return self._java.getStateUpdater()

    @property
    def sub_surface_volume(self) -> float:
        return self._java.getSubSurfaceVolume()

    @sub_surface_volume.setter
    def sub_surface_volume(self, value: float) -> None:
        self._java.setSubSurfaceVolume(value)

    @property
    def trigger_tracker(self) -> "JavaObject":
        return self._java.getTriggerTracker()

    @property
    def velocity(self) -> Vector3:
        return Vector3(self._java.getVelocity())

    @property
    def velocity_extrema_count(self) -> int:
        return self._java.getVelocityExtremaCount()

    @velocity_extrema_count.setter
    def velocity_extrema_count(self, value: int) -> None:
        self._java.setVelocityExtremaCount(value)
