# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit

import java as _java
from pytale.events import Event

_ModifyEvents_BiomeCovers = _java.type(
    "com.hypixel.hytale.builtin.worldgen.modifier.event.ModifyEvents$BiomeCovers"
)

_ModifyEvents_BiomeDynamicLayers = _java.type(
    "com.hypixel.hytale.builtin.worldgen.modifier.event.ModifyEvents$BiomeDynamicLayers"
)

_ModifyEvents_BiomeEnvironments = _java.type(
    "com.hypixel.hytale.builtin.worldgen.modifier.event.ModifyEvents$BiomeEnvironments"
)

_ModifyEvents_BiomeFluids = _java.type(
    "com.hypixel.hytale.builtin.worldgen.modifier.event.ModifyEvents$BiomeFluids"
)

_ModifyEvents_BiomePrefabs = _java.type(
    "com.hypixel.hytale.builtin.worldgen.modifier.event.ModifyEvents$BiomePrefabs"
)

_ModifyEvents_BiomeStaticLayers = _java.type(
    "com.hypixel.hytale.builtin.worldgen.modifier.event.ModifyEvents$BiomeStaticLayers"
)

_ModifyEvents_BiomeTints = _java.type(
    "com.hypixel.hytale.builtin.worldgen.modifier.event.ModifyEvents$BiomeTints"
)

_ModifyEvents_CaveCovers = _java.type(
    "com.hypixel.hytale.builtin.worldgen.modifier.event.ModifyEvents$CaveCovers"
)

_ModifyEvents_CavePrefabs = _java.type(
    "com.hypixel.hytale.builtin.worldgen.modifier.event.ModifyEvents$CavePrefabs"
)

_ModifyEvents_CaveTypes = _java.type(
    "com.hypixel.hytale.builtin.worldgen.modifier.event.ModifyEvents$CaveTypes"
)


class ModifyEvents_BiomeCovers(Event):
    _java_class = _ModifyEvents_BiomeCovers


class ModifyEvents_BiomeDynamicLayers(Event):
    _java_class = _ModifyEvents_BiomeDynamicLayers


class ModifyEvents_BiomeEnvironments(Event):
    _java_class = _ModifyEvents_BiomeEnvironments


class ModifyEvents_BiomeFluids(Event):
    _java_class = _ModifyEvents_BiomeFluids


class ModifyEvents_BiomePrefabs(Event):
    _java_class = _ModifyEvents_BiomePrefabs


class ModifyEvents_BiomeStaticLayers(Event):
    _java_class = _ModifyEvents_BiomeStaticLayers


class ModifyEvents_BiomeTints(Event):
    _java_class = _ModifyEvents_BiomeTints


class ModifyEvents_CaveCovers(Event):
    _java_class = _ModifyEvents_CaveCovers


class ModifyEvents_CavePrefabs(Event):
    _java_class = _ModifyEvents_CavePrefabs


class ModifyEvents_CaveTypes(Event):
    _java_class = _ModifyEvents_CaveTypes
