# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.events import Event

if TYPE_CHECKING:
    from java import JavaObject

_GenerateDefaultLanguageEvent = _java.type(
    "com.hypixel.hytale.server.core.modules.i18n.event.GenerateDefaultLanguageEvent"
)

_MessagesUpdated = _java.type(
    "com.hypixel.hytale.server.core.modules.i18n.event.MessagesUpdated"
)


class GenerateDefaultLanguageEvent(Event):
    _java_class = _GenerateDefaultLanguageEvent


class MessagesUpdated(Event):
    _java_class = _MessagesUpdated

    @property
    def changed_messages(self) -> "JavaObject":
        return self._java.getChangedMessages()

    @property
    def removed_messages(self) -> "JavaObject":
        return self._java.getRemovedMessages()
