# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING
from uuid import UUID

import java as _java
from pytale._uuid import java_uuid_to_python
from pytale.events import Event

if TYPE_CHECKING:
    from java import JavaObject

_TreasureChestOpeningEvent = _java.type(
    "com.hypixel.hytale.builtin.adventure.objectives.events.TreasureChestOpeningEvent"
)


class TreasureChestOpeningEvent(Event):
    _java_class = _TreasureChestOpeningEvent

    @property
    def chest_uuid(self) -> UUID:
        return java_uuid_to_python(self._java.getChestUUID())

    @property
    def objective_uuid(self) -> UUID:
        return java_uuid_to_python(self._java.getObjectiveUUID())

    @property
    def player_ref(self) -> "JavaObject":
        return self._java.getPlayerRef()

    @property
    def store(self) -> "JavaObject":
        return self._java.getStore()
