# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING
from uuid import UUID

import java as _java
from pytale._uuid import java_uuid_to_python
from pytale.components import Component
from pytale.math import Vector3

if TYPE_CHECKING:
    from java import JavaObject

_DeployableComponent = _java.type(
    "com.hypixel.hytale.builtin.deployables.component.DeployableComponent"
)

_DeployableOwnerComponent = _java.type(
    "com.hypixel.hytale.builtin.deployables.component.DeployableOwnerComponent"
)

_DeployableProjectileComponent = _java.type(
    "com.hypixel.hytale.builtin.deployables.component.DeployableProjectileComponent"
)

_DeployableProjectileShooterComponent = _java.type(
    "com.hypixel.hytale.builtin.deployables.component.DeployableProjectileShooterComponent"
)


class DeployableComponent(Component):
    _java_class = _DeployableComponent

    @property
    def config(self) -> "JavaObject":
        return self._java.getConfig()

    @property
    def debug_color(self) -> Vector3:
        return Vector3(self._java.getDebugColor())

    @property
    def owner(self) -> "JavaObject":
        return self._java.getOwner()

    @property
    def owner_uuid(self) -> UUID:
        return java_uuid_to_python(self._java.getOwnerUUID())

    @property
    def spawn_face(self) -> str:
        return self._java.getSpawnFace()

    @property
    def spawn_instant(self) -> "JavaObject":
        return self._java.getSpawnInstant()

    @property
    def time_since_last_attack(self) -> float:
        return self._java.getTimeSinceLastAttack()

    @time_since_last_attack.setter
    def time_since_last_attack(self, value: float) -> None:
        self._java.setTimeSinceLastAttack(value)


class DeployableOwnerComponent(Component):
    _java_class = _DeployableOwnerComponent


class DeployableProjectileComponent(Component):
    _java_class = _DeployableProjectileComponent

    @property
    def previous_tick_position(self) -> Vector3:
        return Vector3(self._java.getPreviousTickPosition())

    @previous_tick_position.setter
    def previous_tick_position(self, value: Vector3) -> None:
        self._java.setPreviousTickPosition(value._java)


class DeployableProjectileShooterComponent(Component):
    _java_class = _DeployableProjectileShooterComponent

    @property
    def active_target(self) -> "JavaObject":
        return self._java.getActiveTarget()

    @active_target.setter
    def active_target(self, value: "JavaObject") -> None:
        self._java.setActiveTarget(value)

    @property
    def projectiles(self) -> "JavaObject":
        return self._java.getProjectiles()

    @property
    def projectiles_for_removal(self) -> "JavaObject":
        return self._java.getProjectilesForRemoval()
