# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.events import Event
from typing_extensions import deprecated

if TYPE_CHECKING:
    from java import JavaObject

_EntityEvent = _java.type(
    "com.hypixel.hytale.server.core.event.events.entity.EntityEvent"
)

_EntityRemoveEvent = _java.type(
    "com.hypixel.hytale.server.core.event.events.entity.EntityRemoveEvent"
)

_LivingEntityUseBlockEvent = _java.type(
    "com.hypixel.hytale.server.core.event.events.entity.LivingEntityUseBlockEvent"
)


class EntityEvent(Event):
    _java_class = _EntityEvent

    @property
    def entity(self) -> "JavaObject":
        return self._java.getEntity()


class EntityRemoveEvent(EntityEvent):
    _java_class = _EntityRemoveEvent


@deprecated("Deprecated in Java")
class LivingEntityUseBlockEvent(Event):
    _java_class = _LivingEntityUseBlockEvent

    @property
    def block_type(self) -> str:
        return self._java.getBlockType()

    @property
    def ref(self) -> "JavaObject":
        return self._java.getRef()
