# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.events import Event

if TYPE_CHECKING:
    from java import JavaObject

_GroupPermissionChangeEvent = _java.type(
    "com.hypixel.hytale.server.core.event.events.permissions.GroupPermissionChangeEvent"
)

_GroupPermissionChangeEvent_Added = _java.type(
    "com.hypixel.hytale.server.core.event.events.permissions.GroupPermissionChangeEvent$Added"
)

_GroupPermissionChangeEvent_Removed = _java.type(
    "com.hypixel.hytale.server.core.event.events.permissions.GroupPermissionChangeEvent$Removed"
)

_PlayerGroupEvent = _java.type(
    "com.hypixel.hytale.server.core.event.events.permissions.PlayerGroupEvent"
)

_PlayerGroupEvent_Added = _java.type(
    "com.hypixel.hytale.server.core.event.events.permissions.PlayerGroupEvent$Added"
)

_PlayerGroupEvent_Removed = _java.type(
    "com.hypixel.hytale.server.core.event.events.permissions.PlayerGroupEvent$Removed"
)

_PlayerPermissionChangeEvent = _java.type(
    "com.hypixel.hytale.server.core.event.events.permissions.PlayerPermissionChangeEvent"
)

_PlayerPermissionChangeEvent_GroupAdded = _java.type(
    "com.hypixel.hytale.server.core.event.events.permissions.PlayerPermissionChangeEvent$GroupAdded"
)

_PlayerPermissionChangeEvent_GroupRemoved = _java.type(
    "com.hypixel.hytale.server.core.event.events.permissions.PlayerPermissionChangeEvent$GroupRemoved"
)

_PlayerPermissionChangeEvent_PermissionsAdded = _java.type(
    "com.hypixel.hytale.server.core.event.events.permissions.PlayerPermissionChangeEvent$PermissionsAdded"
)

_PlayerPermissionChangeEvent_PermissionsRemoved = _java.type(
    "com.hypixel.hytale.server.core.event.events.permissions.PlayerPermissionChangeEvent$PermissionsRemoved"
)


class GroupPermissionChangeEvent(Event):
    _java_class = _GroupPermissionChangeEvent

    @property
    def group_name(self) -> str:
        return self._java.getGroupName()

    class Added(GroupPermissionChangeEvent):
        _java_class = _GroupPermissionChangeEvent_Added

        @property
        def added_permissions(self) -> "JavaObject":
            return self._java.getAddedPermissions()

    class Removed(GroupPermissionChangeEvent):
        _java_class = _GroupPermissionChangeEvent_Removed

        @property
        def removed_permissions(self) -> "JavaObject":
            return self._java.getRemovedPermissions()


class PlayerPermissionChangeEvent(Event):
    _java_class = _PlayerPermissionChangeEvent

    @property
    def player_uuid(self) -> "JavaObject":
        return self._java.getPlayerUuid()

    class GroupAdded(PlayerPermissionChangeEvent):
        _java_class = _PlayerPermissionChangeEvent_GroupAdded

        @property
        def group_name(self) -> str:
            return self._java.getGroupName()

    class GroupRemoved(PlayerPermissionChangeEvent):
        _java_class = _PlayerPermissionChangeEvent_GroupRemoved

        @property
        def group_name(self) -> str:
            return self._java.getGroupName()

    class PermissionsAdded(PlayerPermissionChangeEvent):
        _java_class = _PlayerPermissionChangeEvent_PermissionsAdded

        @property
        def added_permissions(self) -> "JavaObject":
            return self._java.getAddedPermissions()

    class PermissionsRemoved(PlayerPermissionChangeEvent):
        _java_class = _PlayerPermissionChangeEvent_PermissionsRemoved

        @property
        def removed_permissions(self) -> "JavaObject":
            return self._java.getRemovedPermissions()


class PlayerGroupEvent(PlayerPermissionChangeEvent):
    _java_class = _PlayerGroupEvent

    @property
    def group_name(self) -> str:
        return self._java.getGroupName()

    class Added(PlayerGroupEvent):
        _java_class = _PlayerGroupEvent_Added

    class Removed(PlayerGroupEvent):
        _java_class = _PlayerGroupEvent_Removed
