# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.events import AsyncEvent, Cancellable, Event
from pytale.players import PlayerRef
from pytale.world import World
from typing_extensions import deprecated

if TYPE_CHECKING:
    from java import JavaObject

_AddPlayerToWorldEvent = _java.type(
    "com.hypixel.hytale.server.core.event.events.player.AddPlayerToWorldEvent"
)

_DrainPlayerFromWorldEvent = _java.type(
    "com.hypixel.hytale.server.core.event.events.player.DrainPlayerFromWorldEvent"
)

_PlayerChatEvent = _java.type(
    "com.hypixel.hytale.server.core.event.events.player.PlayerChatEvent"
)

_PlayerConnectEvent = _java.type(
    "com.hypixel.hytale.server.core.event.events.player.PlayerConnectEvent"
)

_PlayerCraftEvent = _java.type(
    "com.hypixel.hytale.server.core.event.events.player.PlayerCraftEvent"
)

_PlayerDisconnectEvent = _java.type(
    "com.hypixel.hytale.server.core.event.events.player.PlayerDisconnectEvent"
)

_PlayerEvent = _java.type(
    "com.hypixel.hytale.server.core.event.events.player.PlayerEvent"
)

_PlayerInteractEvent = _java.type(
    "com.hypixel.hytale.server.core.event.events.player.PlayerInteractEvent"
)

_PlayerMouseButtonEvent = _java.type(
    "com.hypixel.hytale.server.core.event.events.player.PlayerMouseButtonEvent"
)

_PlayerMouseMotionEvent = _java.type(
    "com.hypixel.hytale.server.core.event.events.player.PlayerMouseMotionEvent"
)

_PlayerReadyEvent = _java.type(
    "com.hypixel.hytale.server.core.event.events.player.PlayerReadyEvent"
)

_PlayerRefEvent = _java.type(
    "com.hypixel.hytale.server.core.event.events.player.PlayerRefEvent"
)

_PlayerSetupConnectEvent = _java.type(
    "com.hypixel.hytale.server.core.event.events.player.PlayerSetupConnectEvent"
)

_PlayerSetupDisconnectEvent = _java.type(
    "com.hypixel.hytale.server.core.event.events.player.PlayerSetupDisconnectEvent"
)

_RemovedPlayerFromWorldEvent = _java.type(
    "com.hypixel.hytale.server.core.event.events.player.RemovedPlayerFromWorldEvent"
)


class PlayerEvent(Event):
    _java_class = _PlayerEvent

    @property
    def player(self) -> "JavaObject":
        return self._java.getPlayer()

    @property
    def player_ref(self) -> "JavaObject":
        return self._java.getPlayerRef()


class PlayerRefEvent(Event):
    _java_class = _PlayerRefEvent

    @property
    def player_ref(self) -> PlayerRef:
        return PlayerRef(self._java.getPlayerRef())


class AddPlayerToWorldEvent(Event):
    _java_class = _AddPlayerToWorldEvent

    @property
    def holder(self) -> "JavaObject":
        return self._java.getHolder()

    @property
    def join_message(self) -> "JavaObject | None":
        return self._java.getJoinMessage()

    @join_message.setter
    def join_message(self, value: "JavaObject") -> None:
        self._java.setJoinMessage(value)

    @property
    def should_broadcast_join_message(self) -> bool:
        return self._java.shouldBroadcastJoinMessage()

    @should_broadcast_join_message.setter
    def should_broadcast_join_message(self, value: bool) -> None:
        self._java.setBroadcastJoinMessage(value)

    @property
    def world(self) -> World:
        return World(self._java.getWorld())


class DrainPlayerFromWorldEvent(Event):
    _java_class = _DrainPlayerFromWorldEvent

    @property
    def holder(self) -> "JavaObject":
        return self._java.getHolder()

    @property
    def transform(self) -> "JavaObject | None":
        return self._java.getTransform()

    @transform.setter
    def transform(self, value: "JavaObject") -> None:
        self._java.setTransform(value)

    @property
    def world(self) -> World:
        return World(self._java.getWorld())

    @world.setter
    def world(self, value: World) -> None:
        self._java.setWorld(value._java)


class PlayerChatEvent(AsyncEvent, Cancellable):
    _java_class = _PlayerChatEvent

    @property
    def content(self) -> str:
        return self._java.getContent()

    @content.setter
    def content(self, value: str) -> None:
        self._java.setContent(value)

    @property
    def formatter(self) -> "JavaObject":
        return self._java.getFormatter()

    @formatter.setter
    def formatter(self, value: "JavaObject") -> None:
        self._java.setFormatter(value)

    @property
    def sender(self) -> PlayerRef:
        return PlayerRef(self._java.getSender())

    @sender.setter
    def sender(self, value: PlayerRef) -> None:
        self._java.setSender(value._java)

    @property
    def targets(self) -> "JavaObject":
        return self._java.getTargets()

    @targets.setter
    def targets(self, value: "JavaObject") -> None:
        self._java.setTargets(value)


class PlayerConnectEvent(Event):
    _java_class = _PlayerConnectEvent

    @property
    def holder(self) -> "JavaObject":
        return self._java.getHolder()

    @property
    def player(self) -> "JavaObject | None":
        return self._java.getPlayer()

    @property
    def player_ref(self) -> PlayerRef:
        return PlayerRef(self._java.getPlayerRef())

    @property
    def world(self) -> World | None:
        _value = self._java.getWorld()
        return World(_value) if _value is not None else None

    @world.setter
    def world(self, value: World) -> None:
        self._java.setWorld(value._java)


@deprecated("Deprecated in Java")
class PlayerCraftEvent(PlayerEvent):
    _java_class = _PlayerCraftEvent

    @property
    def crafted_recipe(self) -> "JavaObject":
        return self._java.getCraftedRecipe()

    @property
    def quantity(self) -> int:
        return self._java.getQuantity()


class PlayerDisconnectEvent(PlayerRefEvent):
    _java_class = _PlayerDisconnectEvent

    @property
    def disconnect_reason(self) -> "JavaObject":
        return self._java.getDisconnectReason()


@deprecated("Deprecated in Java")
class PlayerInteractEvent(PlayerEvent, Cancellable):
    _java_class = _PlayerInteractEvent

    @property
    def action_type(self) -> "JavaObject":
        return self._java.getActionType()

    @property
    def client_use_time(self) -> int:
        return self._java.getClientUseTime()

    @property
    def item_in_hand(self) -> "JavaObject":
        return self._java.getItemInHand()

    @property
    def target_block(self) -> "JavaObject":
        return self._java.getTargetBlock()

    @property
    def target_entity(self) -> "JavaObject":
        return self._java.getTargetEntity()

    @property
    def target_ref(self) -> "JavaObject":
        return self._java.getTargetRef()


class PlayerMouseButtonEvent(PlayerEvent, Cancellable):
    _java_class = _PlayerMouseButtonEvent

    @property
    def client_use_time(self) -> int:
        return self._java.getClientUseTime()

    @property
    def item_in_hand(self) -> "JavaObject":
        return self._java.getItemInHand()

    @property
    def mouse_button(self) -> "JavaObject":
        return self._java.getMouseButton()

    @property
    def player_ref_component(self) -> PlayerRef:
        return PlayerRef(self._java.getPlayerRefComponent())

    @property
    def screen_point(self) -> "JavaObject":
        return self._java.getScreenPoint()

    @property
    def target_block(self) -> "JavaObject":
        return self._java.getTargetBlock()

    @property
    def target_entity_ref(self) -> "JavaObject":
        return self._java.getTargetEntityRef()


class PlayerMouseMotionEvent(PlayerEvent, Cancellable):
    _java_class = _PlayerMouseMotionEvent

    @property
    def client_use_time(self) -> int:
        return self._java.getClientUseTime()

    @property
    def item_in_hand(self) -> "JavaObject":
        return self._java.getItemInHand()

    @property
    def mouse_motion(self) -> "JavaObject":
        return self._java.getMouseMotion()

    @property
    def screen_point(self) -> "JavaObject":
        return self._java.getScreenPoint()

    @property
    def target_block(self) -> "JavaObject":
        return self._java.getTargetBlock()

    @property
    def target_entity_ref(self) -> "JavaObject":
        return self._java.getTargetEntityRef()


class PlayerReadyEvent(PlayerEvent):
    _java_class = _PlayerReadyEvent

    @property
    def ready_id(self) -> int:
        return self._java.getReadyId()


class PlayerSetupConnectEvent(Event, Cancellable):
    _java_class = _PlayerSetupConnectEvent

    @property
    def auth(self) -> "JavaObject":
        return self._java.getAuth()

    @property
    def client_referral(self) -> "JavaObject | None":
        return self._java.getClientReferral()

    @property
    def is_referral_connection(self) -> bool:
        return self._java.isReferralConnection()

    @property
    def packet_handler(self) -> "JavaObject":
        return self._java.getPacketHandler()

    @property
    def reason(self) -> "JavaObject":
        return self._java.getReason()

    @reason.setter
    def reason(self, value: "JavaObject") -> None:
        self._java.setReason(value)

    @property
    def referral_data(self) -> "JavaObject | None":
        return self._java.getReferralData()

    @property
    def referral_source(self) -> "JavaObject | None":
        return self._java.getReferralSource()

    @property
    def username(self) -> str:
        return self._java.getUsername()

    @property
    def uuid(self) -> "JavaObject":
        return self._java.getUuid()


class PlayerSetupDisconnectEvent(Event):
    _java_class = _PlayerSetupDisconnectEvent

    @property
    def auth(self) -> "JavaObject":
        return self._java.getAuth()

    @property
    def disconnect_reason(self) -> "JavaObject":
        return self._java.getDisconnectReason()

    @property
    def username(self) -> str:
        return self._java.getUsername()

    @property
    def uuid(self) -> "JavaObject":
        return self._java.getUuid()


class RemovedPlayerFromWorldEvent(Event):
    _java_class = _RemovedPlayerFromWorldEvent

    @property
    def holder(self) -> "JavaObject":
        return self._java.getHolder()

    @property
    def leave_message(self) -> "JavaObject | None":
        return self._java.getLeaveMessage()

    @leave_message.setter
    def leave_message(self, value: "JavaObject") -> None:
        self._java.setLeaveMessage(value)

    @property
    def should_broadcast_leave_message(self) -> bool:
        return self._java.shouldBroadcastLeaveMessage()

    @should_broadcast_leave_message.setter
    def should_broadcast_leave_message(self, value: bool) -> None:
        self._java.setBroadcastLeaveMessage(value)

    @property
    def world(self) -> World:
        return World(self._java.getWorld())
