# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING
from uuid import UUID

import java as _java
from pytale._uuid import java_uuid_to_python
from pytale.components import Component
from pytale.world import World

if TYPE_CHECKING:
    from java import JavaObject

_PortalDevice = _java.type("com.hypixel.hytale.builtin.portals.components.PortalDevice")


class PortalDevice(Component):
    _java_class = _PortalDevice

    @property
    def base_block_type(self) -> "JavaObject | None":
        return self._java.getBaseBlockType()

    @property
    def base_block_type_key(self) -> str:
        return self._java.getBaseBlockTypeKey()

    @property
    def config(self) -> "JavaObject":
        return self._java.getConfig()

    @property
    def destination_world(self) -> World | None:
        _value = self._java.getDestinationWorld()
        return World(_value) if _value is not None else None

    @destination_world.setter
    def destination_world(self, value: World) -> None:
        self._java.setDestinationWorld(value._java)

    @property
    def destination_world_uuid(self) -> UUID | None:
        _value = self._java.getDestinationWorldUuid()
        return java_uuid_to_python(_value) if _value is not None else None

    @property
    def is_loading_world(self) -> bool:
        return self._java.isLoadingWorld()
