# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit

import java as _java
from pytale.events import Event

_ItemContainer_ItemContainerChangeEvent = _java.type(
    "com.hypixel.hytale.server.core.inventory.container.ItemContainer$ItemContainerChangeEvent"
)


class ItemContainer_ItemContainerChangeEvent(Event):
    _java_class = _ItemContainer_ItemContainerChangeEvent
