# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING
from uuid import UUID

import java as _java
from pytale._uuid import java_uuid_to_python
from pytale.events import Event

if TYPE_CHECKING:
    from java import JavaObject

_TriggerVolumeEvent = _java.type(
    "com.hypixel.hytale.builtin.triggervolumes.event.TriggerVolumeEvent"
)


class TriggerVolumeEvent(Event):
    _java_class = _TriggerVolumeEvent

    @property
    def entity_ref(self) -> "JavaObject":
        return self._java.getEntityRef()

    @property
    def entity_uuid(self) -> UUID:
        return java_uuid_to_python(self._java.getEntityUuid())

    @property
    def trigger_event_type(self) -> "JavaObject":
        return self._java.getTriggerEventType()

    @property
    def volume_id(self) -> str:
        return self._java.getVolumeId()

    @property
    def volume_tag_indexes(self) -> "JavaObject":
        return self._java.getVolumeTagIndexes()

    @property
    def world_name(self) -> str:
        return self._java.getWorldName()
