# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.events import AsyncEvent, Event

if TYPE_CHECKING:
    from java import JavaObject

_CommonAssetMonitorEvent = _java.type(
    "com.hypixel.hytale.server.core.asset.common.events.CommonAssetMonitorEvent"
)

_SendCommonAssetsEvent = _java.type(
    "com.hypixel.hytale.server.core.asset.common.events.SendCommonAssetsEvent"
)


class CommonAssetMonitorEvent(Event):
    _java_class = _CommonAssetMonitorEvent


class SendCommonAssetsEvent(AsyncEvent):
    _java_class = _SendCommonAssetsEvent

    @property
    def packet_handler(self) -> "JavaObject":
        return self._java.getPacketHandler()

    @property
    def requested_assets(self) -> "JavaObject":
        return self._java.getRequestedAssets()
