# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit

import java as _java
from pytale.events import Event

_PrefabBufferValidator_ValidateBlockEvent = _java.type(
    "com.hypixel.hytale.builtin.blockphysics.PrefabBufferValidator$ValidateBlockEvent"
)


class PrefabBufferValidator_ValidateBlockEvent(Event):
    _java_class = _PrefabBufferValidator_ValidateBlockEvent
