# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING
from uuid import UUID

import java as _java
from pytale._uuid import java_uuid_to_python, python_uuid_to_java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_PatrolPathMarkerEntity = _java.type(
    "com.hypixel.hytale.builtin.path.entities.PatrolPathMarkerEntity"
)


class PatrolPathMarkerEntity(Component):
    _java_class = _PatrolPathMarkerEntity

    @property
    def is_collidable(self) -> bool:
        return self._java.isCollidable()

    @property
    def observation_angle(self) -> float:
        return self._java.getObservationAngle()

    @observation_angle.setter
    def observation_angle(self, value: float) -> None:
        self._java.setObservationAngle(value)

    @property
    def order(self) -> int:
        return self._java.getOrder()

    @order.setter
    def order(self, value: int) -> None:
        self._java.setOrder(value)

    @property
    def parent_path(self) -> "JavaObject":
        return self._java.getParentPath()

    @parent_path.setter
    def parent_path(self, value: "JavaObject") -> None:
        self._java.setParentPath(value)

    @property
    def path_id(self) -> UUID | None:
        _value = self._java.getPathId()
        return java_uuid_to_python(_value) if _value is not None else None

    @path_id.setter
    def path_id(self, value: UUID) -> None:
        self._java.setPathId(python_uuid_to_java(value))

    @property
    def path_name(self) -> str:
        return self._java.getPathName()

    @path_name.setter
    def path_name(self, value: str) -> None:
        self._java.setPathName(value)

    @property
    def pause_time(self) -> float:
        return self._java.getPauseTime()

    @pause_time.setter
    def pause_time(self, value: float) -> None:
        self._java.setPauseTime(value)

    @property
    def temp_path_length(self) -> int:
        return self._java.getTempPathLength()
