# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.events import Event

if TYPE_CHECKING:
    from java import JavaObject

_AllNPCsLoadedEvent = _java.type("com.hypixel.hytale.server.npc.AllNPCsLoadedEvent")


class AllNPCsLoadedEvent(Event):
    _java_class = _AllNPCsLoadedEvent

    @property
    def all_np_cs(self) -> "JavaObject":
        return self._java.getAllNPCs()

    @property
    def loaded_np_cs(self) -> "JavaObject":
        return self._java.getLoadedNPCs()
