# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.events import Event

if TYPE_CHECKING:
    from java import JavaObject

_LoadedNPCEvent = _java.type("com.hypixel.hytale.server.spawning.LoadedNPCEvent")


class LoadedNPCEvent(Event):
    _java_class = _LoadedNPCEvent

    @property
    def builder_info(self) -> "JavaObject":
        return self._java.getBuilderInfo()
