# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit

from uuid import UUID

import java as _java
from pytale._uuid import java_uuid_to_python
from pytale.components import Component
from pytale.math import Vector3

_UsedTeleporter = _java.type(
    "com.hypixel.hytale.builtin.adventure.teleporter.interaction.server.UsedTeleporter"
)


class UsedTeleporter(Component):
    _java_class = _UsedTeleporter

    @property
    def clear_out_xz(self) -> float:
        return self._java.getClearOutXZ()

    @property
    def clear_out_xz_squared(self) -> float:
        return self._java.getClearOutXZSquared()

    @property
    def clear_out_y(self) -> float:
        return self._java.getClearOutY()

    @property
    def destination_position(self) -> Vector3:
        return Vector3(self._java.getDestinationPosition())

    @property
    def destination_world_uuid(self) -> UUID | None:
        _value = self._java.getDestinationWorldUuid()
        return java_uuid_to_python(_value) if _value is not None else None
