# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit

from uuid import UUID

import java as _java
from pytale._uuid import java_uuid_to_python
from pytale.components import Component

_PlacedByInteractionComponent = _java.type(
    "com.hypixel.hytale.server.core.modules.interaction.components.PlacedByInteractionComponent"
)


class PlacedByInteractionComponent(Component):
    _java_class = _PlacedByInteractionComponent

    @property
    def who_placed_uuid(self) -> UUID:
        return java_uuid_to_python(self._java.getWhoPlacedUuid())
