# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.events import Event

if TYPE_CHECKING:
    from java import JavaObject

_AssetMonitorEvent = _java.type("com.hypixel.hytale.assetstore.event.AssetMonitorEvent")

_AssetStoreEvent = _java.type("com.hypixel.hytale.assetstore.event.AssetStoreEvent")

_AssetStoreMonitorEvent = _java.type(
    "com.hypixel.hytale.assetstore.event.AssetStoreMonitorEvent"
)

_AssetsEvent = _java.type("com.hypixel.hytale.assetstore.event.AssetsEvent")

_GenerateAssetsEvent = _java.type(
    "com.hypixel.hytale.assetstore.event.GenerateAssetsEvent"
)

_LoadedAssetsEvent = _java.type("com.hypixel.hytale.assetstore.event.LoadedAssetsEvent")

_RegisterAssetStoreEvent = _java.type(
    "com.hypixel.hytale.assetstore.event.RegisterAssetStoreEvent"
)

_RemoveAssetStoreEvent = _java.type(
    "com.hypixel.hytale.assetstore.event.RemoveAssetStoreEvent"
)

_RemovedAssetsEvent = _java.type(
    "com.hypixel.hytale.assetstore.event.RemovedAssetsEvent"
)


class AssetMonitorEvent(Event):
    _java_class = _AssetMonitorEvent

    @property
    def asset_pack(self) -> str:
        return self._java.getAssetPack()

    @property
    def created_or_modified_directories(self) -> "JavaObject":
        return self._java.getCreatedOrModifiedDirectories()

    @property
    def created_or_modified_files_to_load(self) -> "JavaObject":
        return self._java.getCreatedOrModifiedFilesToLoad()

    @property
    def removed_files_and_directories(self) -> "JavaObject":
        return self._java.getRemovedFilesAndDirectories()

    @property
    def removed_files_to_unload(self) -> "JavaObject":
        return self._java.getRemovedFilesToUnload()


class AssetStoreEvent(Event):
    _java_class = _AssetStoreEvent

    @property
    def asset_store(self) -> "JavaObject":
        return self._java.getAssetStore()


class AssetsEvent(Event):
    _java_class = _AssetsEvent


class AssetStoreMonitorEvent(AssetMonitorEvent):
    _java_class = _AssetStoreMonitorEvent

    @property
    def asset_store(self) -> "JavaObject":
        return self._java.getAssetStore()


class GenerateAssetsEvent(AssetsEvent):
    _java_class = _GenerateAssetsEvent

    @property
    def asset_class(self) -> "JavaObject":
        return self._java.getAssetClass()

    @property
    def asset_map(self) -> "JavaObject":
        return self._java.getAssetMap()

    @property
    def loaded_assets(self) -> "JavaObject":
        return self._java.getLoadedAssets()


class LoadedAssetsEvent(AssetsEvent):
    _java_class = _LoadedAssetsEvent

    @property
    def asset_class(self) -> "JavaObject":
        return self._java.getAssetClass()

    @property
    def asset_map(self) -> "JavaObject":
        return self._java.getAssetMap()

    @property
    def is_initial(self) -> bool:
        return self._java.isInitial()

    @property
    def loaded_assets(self) -> "JavaObject":
        return self._java.getLoadedAssets()

    @property
    def query(self) -> "JavaObject":
        return self._java.getQuery()


class RegisterAssetStoreEvent(AssetStoreEvent):
    _java_class = _RegisterAssetStoreEvent


class RemoveAssetStoreEvent(AssetStoreEvent):
    _java_class = _RemoveAssetStoreEvent


class RemovedAssetsEvent(AssetsEvent):
    _java_class = _RemovedAssetsEvent

    @property
    def asset_class(self) -> "JavaObject":
        return self._java.getAssetClass()

    @property
    def asset_map(self) -> "JavaObject":
        return self._java.getAssetMap()

    @property
    def is_replaced(self) -> bool:
        return self._java.isReplaced()

    @property
    def removed_assets(self) -> "JavaObject":
        return self._java.getRemovedAssets()
