# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING
from uuid import UUID

import java as _java
from pytale._uuid import java_uuid_to_python, python_uuid_to_java
from pytale.components import Component

if TYPE_CHECKING:
    from java import JavaObject

_InitialBeaconDelay = _java.type(
    "com.hypixel.hytale.server.spawning.beacons.InitialBeaconDelay"
)

_LegacySpawnBeaconEntity = _java.type(
    "com.hypixel.hytale.server.spawning.beacons.LegacySpawnBeaconEntity"
)

_SpawnBeacon = _java.type("com.hypixel.hytale.server.spawning.beacons.SpawnBeacon")


class InitialBeaconDelay(Component):
    _java_class = _InitialBeaconDelay


class LegacySpawnBeaconEntity(Component):
    _java_class = _LegacySpawnBeaconEntity

    @property
    def despawn_self_after(self) -> "JavaObject | None":
        return self._java.getDespawnSelfAfter()

    @property
    def is_collidable(self) -> bool:
        return self._java.isCollidable()

    @property
    def is_next_spawn_after_realtime(self) -> bool:
        return self._java.isNextSpawnAfterRealtime()

    @property
    def last_player_count(self) -> int:
        return self._java.getLastPlayerCount()

    @last_player_count.setter
    def last_player_count(self, value: int) -> None:
        self._java.setLastPlayerCount(value)

    @property
    def next_spawn_after(self) -> "JavaObject":
        return self._java.getNextSpawnAfter()

    @property
    def objective_uuid(self) -> UUID | None:
        _value = self._java.getObjectiveUUID()
        return java_uuid_to_python(_value) if _value is not None else None

    @objective_uuid.setter
    def objective_uuid(self, value: UUID) -> None:
        self._java.setObjectiveUUID(python_uuid_to_java(value))

    @property
    def spawn_attempts(self) -> int:
        return self._java.getSpawnAttempts()

    @spawn_attempts.setter
    def spawn_attempts(self, value: int) -> None:
        self._java.setSpawnAttempts(value)

    @property
    def spawn_config_id(self) -> str:
        return self._java.getSpawnConfigId()

    @property
    def spawn_controller(self) -> "JavaObject":
        return self._java.getSpawnController()

    @spawn_controller.setter
    def spawn_controller(self, value: "JavaObject") -> None:
        self._java.setSpawnController(value)

    @property
    def spawn_wrapper(self) -> "JavaObject":
        return self._java.getSpawnWrapper()

    @spawn_wrapper.setter
    def spawn_wrapper(self, value: "JavaObject") -> None:
        self._java.setSpawnWrapper(value)


class SpawnBeacon(Component):
    _java_class = _SpawnBeacon

    @property
    def is_collidable(self) -> bool:
        return self._java.isCollidable()

    @property
    def spawn_config_id(self) -> str:
        return self._java.getSpawnConfigId()

    @property
    def spawn_wrapper(self) -> "JavaObject":
        return self._java.getSpawnWrapper()

    @spawn_wrapper.setter
    def spawn_wrapper(self, value: "JavaObject") -> None:
        self._java.setSpawnWrapper(value)
