# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit

import java as _java
from pytale.events import Event

_Window_WindowCloseEvent = _java.type(
    "com.hypixel.hytale.server.core.entity.entities.player.windows.Window$WindowCloseEvent"
)


class Window_WindowCloseEvent(Event):
    _java_class = _Window_WindowCloseEvent
