# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.events import Event

if TYPE_CHECKING:
    from java import JavaObject

_AssetPackRegisterEvent = _java.type(
    "com.hypixel.hytale.server.core.asset.AssetPackRegisterEvent"
)

_AssetPackUnregisterEvent = _java.type(
    "com.hypixel.hytale.server.core.asset.AssetPackUnregisterEvent"
)

_LoadAssetEvent = _java.type("com.hypixel.hytale.server.core.asset.LoadAssetEvent")


class AssetPackRegisterEvent(Event):
    _java_class = _AssetPackRegisterEvent

    @property
    def asset_pack(self) -> "JavaObject":
        return self._java.getAssetPack()


class AssetPackUnregisterEvent(Event):
    _java_class = _AssetPackUnregisterEvent

    @property
    def asset_pack(self) -> "JavaObject":
        return self._java.getAssetPack()


class LoadAssetEvent(Event):
    _java_class = _LoadAssetEvent

    @property
    def boot_start(self) -> int:
        return self._java.getBootStart()

    @property
    def is_should_shutdown(self) -> bool:
        return self._java.isShouldShutdown()

    @property
    def reasons(self) -> "JavaObject":
        return self._java.getReasons()
