# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.events import AsyncEvent, Event

if TYPE_CHECKING:
    from java import JavaObject

_AssetEditorActivateButtonEvent = _java.type(
    "com.hypixel.hytale.builtin.asseteditor.event.AssetEditorActivateButtonEvent"
)

_AssetEditorAssetCreatedEvent = _java.type(
    "com.hypixel.hytale.builtin.asseteditor.event.AssetEditorAssetCreatedEvent"
)

_AssetEditorClientDisconnectEvent = _java.type(
    "com.hypixel.hytale.builtin.asseteditor.event.AssetEditorClientDisconnectEvent"
)

_AssetEditorFetchAutoCompleteDataEvent = _java.type(
    "com.hypixel.hytale.builtin.asseteditor.event.AssetEditorFetchAutoCompleteDataEvent"
)

_AssetEditorRequestDataSetEvent = _java.type(
    "com.hypixel.hytale.builtin.asseteditor.event.AssetEditorRequestDataSetEvent"
)

_AssetEditorSelectAssetEvent = _java.type(
    "com.hypixel.hytale.builtin.asseteditor.event.AssetEditorSelectAssetEvent"
)

_AssetEditorUpdateWeatherPreviewLockEvent = _java.type(
    "com.hypixel.hytale.builtin.asseteditor.event.AssetEditorUpdateWeatherPreviewLockEvent"
)

_EditorClientEvent = _java.type(
    "com.hypixel.hytale.builtin.asseteditor.event.EditorClientEvent"
)


class EditorClientEvent(Event):
    _java_class = _EditorClientEvent

    @property
    def editor_client(self) -> "JavaObject":
        return self._java.getEditorClient()


class AssetEditorActivateButtonEvent(EditorClientEvent):
    _java_class = _AssetEditorActivateButtonEvent

    @property
    def button_id(self) -> str:
        return self._java.getButtonId()


class AssetEditorAssetCreatedEvent(EditorClientEvent):
    _java_class = _AssetEditorAssetCreatedEvent

    @property
    def asset_path(self) -> "JavaObject":
        return self._java.getAssetPath()

    @property
    def asset_type(self) -> str:
        return self._java.getAssetType()

    @property
    def button_id(self) -> str:
        return self._java.getButtonId()

    @property
    def data(self) -> "JavaObject":
        return self._java.getData()


class AssetEditorClientDisconnectEvent(EditorClientEvent):
    _java_class = _AssetEditorClientDisconnectEvent

    @property
    def disconnect_reason(self) -> "JavaObject":
        return self._java.getDisconnectReason()


class AssetEditorFetchAutoCompleteDataEvent(AsyncEvent):
    _java_class = _AssetEditorFetchAutoCompleteDataEvent

    @property
    def data_set(self) -> str:
        return self._java.getDataSet()

    @property
    def editor_client(self) -> "JavaObject":
        return self._java.getEditorClient()

    @property
    def query(self) -> str:
        return self._java.getQuery()

    @property
    def results(self) -> "JavaObject":
        return self._java.getResults()

    @results.setter
    def results(self, value: "JavaObject") -> None:
        self._java.setResults(value)


class AssetEditorRequestDataSetEvent(AsyncEvent):
    _java_class = _AssetEditorRequestDataSetEvent

    @property
    def data_set(self) -> str:
        return self._java.getDataSet()

    @property
    def editor_client(self) -> "JavaObject":
        return self._java.getEditorClient()

    @property
    def results(self) -> "JavaObject":
        return self._java.getResults()

    @results.setter
    def results(self, value: "JavaObject") -> None:
        self._java.setResults(value)


class AssetEditorSelectAssetEvent(EditorClientEvent):
    _java_class = _AssetEditorSelectAssetEvent

    @property
    def asset_file_path(self) -> "JavaObject":
        return self._java.getAssetFilePath()

    @property
    def asset_type(self) -> str:
        return self._java.getAssetType()

    @property
    def previous_asset_file_path(self) -> "JavaObject":
        return self._java.getPreviousAssetFilePath()

    @property
    def previous_asset_type(self) -> str:
        return self._java.getPreviousAssetType()


class AssetEditorUpdateWeatherPreviewLockEvent(EditorClientEvent):
    _java_class = _AssetEditorUpdateWeatherPreviewLockEvent

    @property
    def is_locked(self) -> bool:
        return self._java.isLocked()
