# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.events import Cancellable, Event
from pytale.world import World

if TYPE_CHECKING:
    from java import JavaObject

_AddWorldEvent = _java.type(
    "com.hypixel.hytale.server.core.universe.world.events.AddWorldEvent"
)

_AllWorldsLoadedEvent = _java.type(
    "com.hypixel.hytale.server.core.universe.world.events.AllWorldsLoadedEvent"
)

_ChunkEvent = _java.type(
    "com.hypixel.hytale.server.core.universe.world.events.ChunkEvent"
)

_ChunkPreLoadProcessEvent = _java.type(
    "com.hypixel.hytale.server.core.universe.world.events.ChunkPreLoadProcessEvent"
)

_RemoveWorldEvent = _java.type(
    "com.hypixel.hytale.server.core.universe.world.events.RemoveWorldEvent"
)

_StartWorldEvent = _java.type(
    "com.hypixel.hytale.server.core.universe.world.events.StartWorldEvent"
)

_WorldEvent = _java.type(
    "com.hypixel.hytale.server.core.universe.world.events.WorldEvent"
)

_WorldGenChunksClearedEvent = _java.type(
    "com.hypixel.hytale.server.core.universe.world.events.WorldGenChunksClearedEvent"
)


class ChunkEvent(Event):
    _java_class = _ChunkEvent

    @property
    def chunk(self) -> "JavaObject":
        return self._java.getChunk()


class WorldEvent(Event):
    _java_class = _WorldEvent

    @property
    def world(self) -> World:
        return World(self._java.getWorld())


class AddWorldEvent(WorldEvent, Cancellable):
    _java_class = _AddWorldEvent


class AllWorldsLoadedEvent(Event):
    _java_class = _AllWorldsLoadedEvent


class ChunkPreLoadProcessEvent(ChunkEvent):
    _java_class = _ChunkPreLoadProcessEvent

    @property
    def holder(self) -> "JavaObject":
        return self._java.getHolder()

    @property
    def is_newly_generated(self) -> bool:
        return self._java.isNewlyGenerated()


class RemoveWorldEvent(WorldEvent, Cancellable):
    _java_class = _RemoveWorldEvent

    @property
    def removal_reason(self) -> "JavaObject":
        return self._java.getRemovalReason()


class StartWorldEvent(WorldEvent):
    _java_class = _StartWorldEvent


class WorldGenChunksClearedEvent(WorldEvent):
    _java_class = _WorldGenChunksClearedEvent
