# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.events import Event

if TYPE_CHECKING:
    from java import JavaObject

_WorldPathChangedEvent = _java.type(
    "com.hypixel.hytale.server.core.universe.world.path.WorldPathChangedEvent"
)


class WorldPathChangedEvent(Event):
    _java_class = _WorldPathChangedEvent

    @property
    def world_path(self) -> "JavaObject":
        return self._java.getWorldPath()
