# Auto-generated by pytale-tools from Server-0.5.6.jar — do not edit
from typing import TYPE_CHECKING

import java as _java
from pytale.events import Event
from typing_extensions import deprecated

if TYPE_CHECKING:
    from java import JavaObject

_BootEvent = _java.type("com.hypixel.hytale.server.core.event.events.BootEvent")

_PrepareUniverseEvent = _java.type(
    "com.hypixel.hytale.server.core.event.events.PrepareUniverseEvent"
)

_ShutdownEvent = _java.type("com.hypixel.hytale.server.core.event.events.ShutdownEvent")


class BootEvent(Event):
    _java_class = _BootEvent


@deprecated("Deprecated in Java")
class PrepareUniverseEvent(Event):
    _java_class = _PrepareUniverseEvent

    @property
    def world_config_provider(self) -> "JavaObject":
        return self._java.getWorldConfigProvider()

    @world_config_provider.setter
    def world_config_provider(self, value: "JavaObject") -> None:
        self._java.setWorldConfigProvider(value)


class ShutdownEvent(Event):
    _java_class = _ShutdownEvent
